version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: scm20
    ports:
      - "3307:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123

    ports:
      - "8081:80"
    depends_on:
      - mysql
  springboot:
    build: .
    container_name: scm_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scm20
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      EMAIL_HOST: live.smtp.mailtrap.io
      EMAIL_PORT: 587
      EMAIL_USERNAME: smtp@mailtrap.io
      EMAIL_PASSWORD: 5768df1ccd635d6bae267f486a0eec40
      EMAIL_DOMAIN: demomailtrap.com
      CLOUDINARY_API_KEY: 341269256337173
      CLOUDINARY_API_SECRET: YM3jsTYULLVrjbA5X_lLJQrLJ1g
      CLOUDINARY_NAME: dpvxhmfu2
    ports:
      - "8082:8080"
    depends_on:
      - mysql
volumes:
  mysql_data:
